# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
